apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fhfu2l3w4-go
  janus-idp.io/tekton: fhfu2l3w4-go
  backstage.io/kubernetes-id: fhfu2l3w4-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fhfu2l3w4-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
